### ISSUE TITLE
Missing dep for tests

### ISSUE THREAD

**Issue by Wardormeur** [mcollina/seneca-queue#11]
Mocha is a missing dep when running the tests :)

**Comment by geek** [comment]
I just cloned and ran install, then ran `npm test`, no issues... no references to mocha exist.

**Comment by geek** [comment]
I also ran find for `mocha`, nothing in the project.  @Wardormeur if you can reproduce an issue, please link to the offending code and reopen.

**Comment by Wardormeur** [comment]
I figured out why I guess : 
when doing an npm isntall seneca-queue, it seems to take the one from github.com/mcollina/seneca-queue; which indeed redirect to this one on github, but probably don't for npm

**Comment by geek** [comment]
@Wardormeur thanks for pointing that out.  I just published a new version with updated links and tests.

**Comment by Wardormeur** [comment]
Thanks :+1:
