### ISSUE TITLE
"Automagic" queues discovery: behaviour and problems

### ISSUE THREAD

**Issue by paolochiodi** [mcollina/seneca-queue#7]
At the moment external queue implementation are discovered automatically by searching for registered actions with the appropriate "hook" pattern. Requests are then distributed among found implementations with a round robin algorithm.

I think this may cause two problems:
- seneca queue can't pass options to the external implementations leaving the burden to to so to the final users, which is counter intuitive (especially when changing "role")
- this makes difficult to have different implementations at the same time - because seneca-queue split the requests among all the different implementations. It could be useful to allow the split to be based on the task type

We may also want to create a seneca-queue-test package to check for queues conformity (along the lines of seneca-store-test and seneca-transport-test)

**Comment by mcollina** [comment]
How would you change it? I'm ok for a solution for both problems.

We should also implement at least one or two other queue transports.

**Comment by paolochiodi** [comment]
For the first one I guess the easiest path would be to call an "hook:init" action on the implementation, passing in the options and any other useful information. This way it will also support the init on transport/remote queues.

For the task on different queues I don't have a strong opinion. The current way would be to have a different role for each queue "type", and maybe this could be enough. Perhaps we can force this by progressively changing the role for each queue ( queue, queue1...)
Other options maybe allowing to pass a "type" alongside the start,stop,queue commands. 
I need more thinking on this.

**Comment by paolochiodi** [comment]
I just realised that the init may not be a feasible path, because we need the implementing queue to be fully registered to discover it to send it the hook:init, but it would need the hook:init to properly register

**Comment by mcollina** [comment]
I have no strong feelings about either of these issues. I just think we need this pattern in the seneca ecosystem.

I would say code wins, so send a PR :).

**Comment by paolochiodi** [comment]
Yeah, I need more time to think how to solve that. Will do sometime this week
